const PROJECTS = {
  portal: {
    title: "University Academic Portal",
    subtitle: "Vue.js & Laravel · FYP",
    period: "Aug 2025 – Apr 2026",
    role: "Full Stack Developer",
    org: "University of Greenwich",
    tech: ["PHP", "Laravel", "Vue.js", "Inertia.js", "MySQL", "Tailwind CSS", "Vite", "Stripe", "PHPUnit"],
    color: "indigo",
    bullets: [
      "Designed and developed a multi-user University Academic Portal for students, teachers, staff, and guests.",
      "Implemented registration, enrolment, grades, assignments, fee payment, timetables, attendance, announcements, messaging, and notifications.",
      "Delivered RBAC, relational database design, validation, GPA calculation, search, email verification, and responsive UIs.",
      "Integrated Stripe Checkout with webhooks; built queue-backed notifications and scheduled jobs for attendance alerts.",
      "Applied Agile DSDM (MoSCoW, timeboxing, usability testing); produced ER diagrams, use cases, sequence/class diagrams, test plans, and LESPI evaluation aligned with BCS standards.",
    ],
    github: "portal",
    demo: "portal",
  },
  elitearticles: {
    title: "EliteArticles Magazine System",
    subtitle: "Annual University Magazine",
    period: "Jan 2026 – Apr 2026",
    role: "Team Leader & Backend Developer",
    org: "University of Greenwich",
    tech: ["PHP", "Laravel", "MySQL", "Blade", "Jira", "PHPUnit"],
    color: "violet",
    bullets: [
      "Led delivery using Agile Scrum, sprint planning, and coordination via Jira and GitHub.",
      "Built authentication, RBAC, contribution workflows, coordinator review, manager reporting (ZIP export), and faculty-scoped guest access.",
      "Designed relational schemas, ERDs, and validation; produced user stories, test plans, sitemaps, and class diagrams.",
    ],
    github: "elitearticles",
    demo: "elitearticles",
  },
  mhike: {
    title: "M-Hike",
    subtitle: "Android & React Native",
    period: "Aug 2025 – Dec 2025",
    role: "Mobile Developer",
    org: "University of Greenwich",
    tech: ["Kotlin", "React Native", "Expo", "SQLite", "TypeScript"],
    color: "emerald",
    bullets: [
      "Native Android: full CRUD for hikes and observations, layered SQLite architecture, Material Design, RecyclerView lists.",
      "Cross-platform: file-based navigation, GPS, reverse geocoding, camera/gallery, OpenWeatherMap, Formik/Yup validation.",
      "Applied HCI principles, ConstraintLayout, themes, and navigation patterns.",
    ],
    github: "mhike-android",
    demo: null,
  },
  android: {
    title: "Android Development Portfolio",
    subtitle: "Practical Projects",
    period: "Aug 2025 – Dec 2025",
    role: "Android Developer",
    org: "University of Greenwich",
    tech: ["Kotlin", "Room", "RecyclerView", "Material Design"],
    color: "sky",
    bullets: [
      "Calculator: arithmetic operations, decimal input, validation, divide-by-zero handling, Toast feedback, animations.",
      "Contact Manager: Room storage, RecyclerView, coroutines, DAO/repository pattern, form validation.",
      "Image Viewer: gallery navigation, fade animations, on-screen image counter.",
    ],
    github: null,
    demo: null,
  },
  libraria: {
    title: "Libraria Library System",
    subtitle: "NCC Level 5 Graduation Assignment",
    period: "Jan 2025 – May 2025",
    role: "Web Developer & Database Designer",
    org: "NCC Education",
    tech: ["PHP", "MySQL", "Bootstrap", "jQuery"],
    color: "teal",
    bullets: [
      "Digitized book, member, staff, borrowing, return, fine, and feedback workflows with admin reporting charts.",
      "Designed database schema with use cases, class/sequence diagrams, and functional requirements.",
      "Applied DSDM (MoSCoW, timeboxing, SWOT, risk management, LESPI); delivered testing and deployment planning.",
    ],
    github: "libraria",
    demo: "libraria",
  },
  smcworld: {
    title: "SMCWorld Campaign Website",
    subtitle: "Dynamic Website · NCC L5",
    period: "Jul 2024 – Dec 2024",
    role: "PHP Web Developer",
    org: "NCC Education",
    tech: ["PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    color: "amber",
    bullets: [
      "Built public and admin interfaces with authentication, registration, contact forms, and search.",
      "Implemented CRUD, relational schema, responsive CSS, reCAPTCHA, and Google Translate integration.",
    ],
    github: "smcworld",
    demo: "smcworld",
  },
  nature: {
    title: "Nature Explore",
    subtitle: "HCI Tablet Prototype",
    period: "Aug 2025 – Dec 2025",
    role: "UI/UX Designer & Prototype Developer",
    org: "University of Greenwich",
    tech: ["Axure RP 11", "HCI"],
    color: "cyan",
    bullets: [
      "Designed a mid-fidelity tablet prototype for child-friendly nature learning (quizzes, maps, progress, parent dashboard concepts).",
      "Applied accessibility, cognitive psychology, and interaction design; produced user flows, sitemaps, and conceptual diagrams.",
    ],
    github: null,
    demo: null,
  },
  camping: {
    title: "K Camping World (RCC)",
    subtitle: "E-Commerce Website · NCC L4",
    period: "NCC Level 4",
    role: "Front-end Developer",
    org: "NCC Education",
    tech: ["HTML", "CSS"],
    color: "orange",
    bullets: [
      "Responsive multi-page e-commerce site: catalogues, basket UI, W3C validation, YouTube/Maps/PDF embeds.",
    ],
    github: "camping",
    demo: "camping",
  },
};

const PROJECT_CATEGORIES = [
  { id: "web", label: "Web Development", ids: ["portal", "elitearticles", "libraria", "smcworld", "camping"] },
  { id: "mobile", label: "Mobile", ids: ["mhike", "android"] },
  { id: "ux", label: "UI/UX", ids: ["nature"] },
];

const ANALYSIS_PROJECTS = [
  { title: "Bright Care Health Ltd — Telehealth Platform", period: "Sep 2025 – Dec 2025", desc: "Agile requirements, MoSCoW, stakeholder analysis, GDPR, privacy-by-design, RBAC, BCS-aligned recommendations." },
  { title: "Wellcome Housing — Network Security", period: "Mar 2025 – May 2025", desc: "Risk assessment; VPN, firewall, DMZ, IDS, MFA, encryption; mitigations for Log4Shell, SQLi, phishing, ransomware." },
  { title: "Infinity Games — Information Systems", period: "Sep 2024 – Dec 2024", desc: "Methodology comparison; CATWOE, Rich Picture, PEST, business process modelling." },
  { title: "GeekUp — Agile Development Planning", period: "Jan 2025 – Apr 2025", desc: "DSDM planning, user stories, timeboxing, UML, MVP, proof-of-concept for mobile trading platform." },
  { title: "Gotham City College — Network Design", period: "Jan 2024 – Apr 2024", desc: "VLAN/WiFi 6 topology, VPN, security controls, scalable campus infrastructure planning." },
];

const OTHER_PROJECTS = [
  { title: "Walmart Retail Sales Database (L5)", desc: "SQL Server: ERD, 1NF–3NF normalization, joins, views, reporting queries." },
  { title: "Fitness Tracker Desktop App (L4)", desc: "C# WinForms + SQL Server: MET calories, goals, CRUD, DataGridViews." },
  { title: "McDonald's Restaurant Database (L4)", desc: "SQL relational design for menu, orders, ingredients." },
  { title: "Fordley Car Parking Office System (L4)", desc: "Excel VBA forms, mail merge, ERD design, parking workflow analysis." },
  { title: "Connect 4 Game (L3)", desc: "VB.NET WinForms: game logic, save/load, testing documentation." },
  { title: "Computer Systems Portfolio (L4)", desc: "Windows 10 installation, drivers, troubleshooting, maintenance documentation." },
];
