const PROJECTS = {
  portal: {
    title: "University Academic Portal",
    subtitle: "Vue.js & Laravel · Individual FYP",
    period: "Aug 2025 – Apr 2026",
    role: "Full Stack Developer · System Analyst · Database Designer",
    org: "University of Greenwich",
    tech: ["PHP", "Laravel", "Vue.js", "Inertia.js", "MySQL", "Tailwind CSS", "Vite", "Git", "GitHub", "Stripe", "PHPUnit"],
    bullets: [
      "Designed and developed a multi-user University Academic Portal to manage academic workflows for students, teachers, staff, and guests.",
      "Implemented modules including student registration, course enrolment, grade management, assignments, fee payment, timetables, attendance, announcements, messaging, and notifications.",
      "Applied Agile DSDM with iterative development, MoSCoW prioritization, timeboxing, usability testing, and continuous evaluation.",
      "Designed relational database structures, RBAC authentication workflows, validation systems, and secure multi-role backend logic.",
      "Produced ER diagrams, use case diagrams, sequence diagrams, class diagrams, functional requirements, test plans, and usability evaluations.",
      "Integrated GPA calculation, attendance alerts, Stripe payment workflows, search systems, email verification, and responsive UIs.",
      "Deployed a live demo on Railway for portfolio review and interviews.",
      "Built queue-backed notifications and scheduled jobs for attendance alerts and system messaging.",
      "Implemented Stripe Checkout and webhook handling with automated payment processing and PHPUnit feature tests.",
      "Conducted functional testing, usability testing, risk management analysis, and LESPI evaluation aligned with BCS standards.",
    ],
    github: "portal",
    demo: "portal",
  },
  elitearticles: {
    title: "EliteArticles — Annual University Magazine System",
    subtitle: "Final Year Group Project",
    period: "Jan 2026 – Apr 2026",
    role: "Team Leader · Backend Developer · Database Designer",
    org: "University of Greenwich & KMD College",
    tech: ["PHP", "Laravel", "MySQL", "Blade", "Git", "GitHub", "Jira", "PHPUnit"],
    bullets: [
      "Led the university group project using Agile Scrum, coordinating technical tasks, sprint planning, and team delivery via Jira and GitHub.",
      "Developed backend features including authentication, RBAC, contribution submission workflows, reporting, and in-app notifications.",
      "Designed and maintained relational database structures, ERDs, validation rules, and secure multi-user data flows.",
      "Delivered a multi-role web system supporting students, coordinators, managers, admins, and guests across submission, review, reporting, and publication workflows.",
      "Implemented student file uploads, coordinator review and selection, manager reporting with ZIP export, and faculty-scoped guest access.",
      "Produced test plans, user stories, MoSCoW prioritization, use case diagrams, sitemaps, ERDs, and class diagrams.",
      "Participated in sprint reviews, retrospectives, testing, and iterative feature delivery across the full software lifecycle.",
    ],
    github: "elitearticles",
    demo: null,
  },
  "mhike-android": {
    title: "M-Hike — Native Android Application",
    subtitle: "Mobile Application Development",
    period: "Aug 2025 – Dec 2025",
    role: "Mobile Developer",
    org: "University of Greenwich",
    tech: ["Kotlin", "Android SDK", "SQLite", "Material Design", "XML"],
    bullets: [
      "Developed a native Android hiking management app in Kotlin for creating, viewing, editing, and deleting hikes and observations.",
      "Implemented SQLite persistence with a layered data architecture (database helper, repositories, CRUD operations).",
      "Built input validation, confirmation screens, and structured hike/observation forms with optional metadata (trail type, duration, elevation, weather/season).",
      "Added advanced search and filtering (name, location, length, date) with RecyclerView-based lists and Material Design UI.",
      "Applied HCI principles and responsive Android layouts using ConstraintLayout, themes, and navigation patterns.",
    ],
    github: "mhike-android",
    demo: null,
  },
  "mhike-rn": {
    title: "M-Hike — Cross-Platform Application (React Native)",
    subtitle: "Mobile Application Development",
    period: "Aug 2025 – Dec 2025",
    role: "Mobile Developer",
    org: "University of Greenwich",
    tech: ["TypeScript", "React Native", "Expo", "SQLite", "Formik", "Yup", "React Native Paper"],
    bullets: [
      "Developed a cross-platform hike management app using React Native and Expo, with file-based navigation and a modular service-layer architecture.",
      "Implemented full CRUD for hikes with SQLite local persistence and typed data models.",
      "Integrated GPS location, reverse geocoding, camera/gallery photo capture, and OpenWeatherMap weather data on hike detail screens.",
      "Built validated forms (Formik + Yup) and responsive UIs using React Native Paper across Android, iOS, and Web.",
      "Applied HCI and Material Design principles for usability, including themed layouts, tab navigation, and external map linking from stored coordinates.",
    ],
    github: "mhike-rn",
    demo: null,
  },
  android: {
    title: "Android Development Portfolio",
    subtitle: "Practical Projects",
    period: "Aug 2025 – Dec 2025",
    role: "Android Developer",
    org: "University of Greenwich",
    tech: ["Kotlin", "Android SDK", "Room", "RecyclerView", "Material Design", "Coroutines"],
    bullets: [
      "Calculator: structured XML layouts (LinearLayout, GridLayout), arithmetic (+, −, ×, ÷), decimal input, validation, divide-by-zero handling, Toast feedback, and bounce animations.",
      "Contact Manager: Room storage, RecyclerView, Kotlin Coroutines, DAO/repository pattern, form validation, and custom adapters.",
      "Image Viewer: gallery-style navigation with drawable resources, circular previous/next controls, fade animations, and on-screen image counter.",
    ],
    githubRepos: [
      { label: "Contact Manager", key: "android-contacts" },
      { label: "Calculator", key: "android-calculator" },
      { label: "Image Viewer", key: "android-imageviewer" },
    ],
    demo: null,
  },
  nature: {
    title: "Nature Explore — HCI Educational Tablet Application",
    subtitle: "Human Computer Interaction Project",
    period: "Aug 2025 – Dec 2025",
    role: "UI/UX Designer · Prototype Developer",
    org: "University of Greenwich",
    tech: ["Axure RP 11", "UI/UX Design", "HCI Principles"],
    bullets: [
      "Designed a mid-fidelity interactive tablet application prototype for children to explore animals, plants, and nature through educational activities.",
      "Developed the prototype with features including AR scanning, quizzes, mini-games, interactive maps, progress tracking, and parent dashboards.",
      "Applied HCI theories, accessibility guidelines, cognitive psychology principles, and interaction design concepts throughout the project.",
      "Designed user flows, site maps, conceptual diagrams, and interface structures focused on usability and child-friendly interaction.",
      "Conducted research on gamification, AR learning, multimodal interaction, accessibility, and educational application design.",
    ],
    github: "nature",
    demo: null,
  },
  libraria: {
    title: "Libraria — Library Management System",
    subtitle: "Level 5 Graduation Assignment",
    period: "Jan 2025 – May 2025",
    role: "Web Developer · System Analyst · Database Designer",
    org: "NCC Education · Level 5 Diploma in Computing",
    tech: ["PHP", "MySQL", "HTML", "CSS", "JavaScript", "Bootstrap", "jQuery"],
    bullets: [
      "Developed a web-based library management system to digitize book, member, staff, borrowing, return, fine, and feedback processes.",
      "Implemented member and staff workflows including registration/login, book catalog, borrow cart, returns, overdue status, fine viewing, and admin dashboards with reporting charts.",
      "Analyzed manual library workflows and defined requirements covering records, membership, borrowing, returns, overdue handling, and feedback.",
      "Designed database schema and supporting models (use cases, class/sequence diagrams, prototypes, functional requirements).",
      "Applied Agile DSDM practices including MoSCoW prioritization, timeboxing, SWOT, risk management, and LESPI evaluation.",
      "Delivered functional and usability testing, deployment planning, data migration planning, and user training documentation.",
    ],
    github: "libraria",
    demo: null,
  },
  smcworld: {
    title: "SMCWorld — Social Media Campaign Website",
    subtitle: "Dynamic Website Development · NCC L5",
    period: "Jul 2024 – Dec 2024",
    role: "PHP Web Developer · Database Designer",
    org: "NCC Education",
    tech: ["PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    bullets: [
      "Developed a dynamic social media safety and campaign website with separate public and admin interfaces.",
      "Implemented user authentication, registration, contact forms, and search modules using PHP and MySQL.",
      "Designed relational database tables for users, campaigns, safety tips, legislation, livestreaming, and participation records.",
      "Built responsive UI with custom CSS, media queries, animations, and structured multi-page navigation.",
      "Delivered CRUD operations for users and content, search filtering, Google reCAPTCHA, and Google Translate integration.",
      "Supported campaign participation and social media safety education through user-focused content workflows.",
    ],
    github: "smcworld",
    demo: null,
  },
  camping: {
    title: "K Camping World (RCC) — Camping Equipment E-Commerce",
    subtitle: "Web Development · NCC L4",
    period: "NCC Level 4",
    role: "Front-end Developer",
    org: "NCC Education",
    tech: ["HTML", "CSS", "Responsive Design", "W3C Validation"],
    bullets: [
      "Designed and developed a responsive multi-page camping equipment e-commerce website with product catalogues, customer reviews, shopping basket UI, and registration/login interfaces.",
      "Built responsive layouts, navigation, CSS image slideshows, promotional modal pop-ups (:target), media queries, and CSS animations.",
      "Applied basic accessibility practices including alt text on images, form placeholders, and structured page layout.",
      "Carried out W3C HTML/CSS validation and cross-device responsive checks on desktop and mobile viewports.",
      "Embedded multimedia content including YouTube videos, Google Maps, and PDF documents.",
    ],
    github: "camping",
    demo: null,
  },
  brightcare: {
    title: "Bright Care Health Ltd — Telehealth Platform Analysis",
    subtitle: "Requirements Management & System Analysis",
    period: "University of Greenwich",
    role: "System Analyst",
    org: "University of Greenwich",
    tech: ["Agile Scrum", "MoSCoW", "GDPR", "RBAC"],
    bullets: [
      "Conducted Agile requirements analysis and system evaluation for a healthcare telehealth platform case study.",
      "Applied MoSCoW prioritization, stakeholder analysis, and high-level functional requirement modeling techniques.",
      "Evaluated legal, social, ethical, and professional considerations including GDPR compliance, privacy-by-design, RBAC security, and governance responsibilities.",
      "Analyzed Agile Scrum suitability, MVP planning, scalability considerations, and stakeholder collaboration within an 8-week development timebox.",
      "Produced structured technical documentation and compliance-focused recommendations aligned with BCS professional standards.",
    ],
    github: null,
    demo: null,
  },
  infinity: {
    title: "Infinity Games — Information Systems Analysis",
    subtitle: "NCC Level 5",
    period: "NCC Education",
    role: "System Analyst · Business Process Analyst",
    org: "NCC Education",
    tech: ["Agile", "Waterfall", "CATWOE", "PEST", "BPM"],
    bullets: [
      "Conducted information systems analysis for a game development company scenario focusing on organizational, technical, and stakeholder challenges.",
      "Compared Agile, Waterfall, Prototyping, and User-Centered Design methodologies for system development and project management.",
      "Applied CATWOE analysis, Rich Picture modeling, PEST analysis, and Business Process Modeling techniques to evaluate business operations and workflows.",
      "Designed a project management dashboard prototype and analyzed process-oriented and people-oriented information system methodologies.",
      "Produced structured analytical documentation, evaluations, and recommendations for improving organizational workflows and system effectiveness.",
    ],
    github: "infinity",
    demo: null,
  },
  wellcome: {
    title: "Wellcome Housing Association — Network Security Analysis",
    subtitle: "Network Security & Cryptography · NCC L5",
    period: "NCC Education",
    role: "Security Analyst",
    org: "NCC Education",
    tech: ["VPN", "Firewall", "DMZ", "IDS", "RBAC", "MFA", "GDPR"],
    bullets: [
      "Conducted cybersecurity risk assessment and threat analysis for a housing association network infrastructure handling sensitive tenant and financial data.",
      "Evaluated network security controls including VPN architecture, firewalls, DMZ configuration, intrusion detection systems (IDS), RBAC, MFA, and encryption strategies.",
      "Analyzed software vulnerabilities including Log4Shell, SQL Injection, HTTP security risks, ransomware threats, phishing attacks, and cloud misconfigurations.",
      "Proposed security countermeasures including SSL/TLS, AES-256 encryption, cloud backup strategies, disaster recovery planning, and secure authentication controls.",
      "Designed secure network architecture diagrams and produced technical documentation aligned with GDPR compliance and cybersecurity best practices.",
    ],
    github: null,
    demo: null,
  },
  geekup: {
    title: "GeekUp — Agile Development Project",
    subtitle: "Agile System Analysis & Software Planning · NCC L5",
    period: "NCC Education",
    role: "Business Analyst · System Designer",
    org: "NCC Education",
    tech: ["DSDM", "UML", "MoSCoW", "MVP"],
    bullets: [
      "Applied DSDM Agile framework to plan and manage the development lifecycle of a mobile trading platform project.",
      "Created system analysis documents including user stories, requirement analysis, timeboxing plans, UML class diagrams, and sequence diagrams.",
      "Designed Agile project workflows using MoSCoW prioritization, MVP planning, prototyping, and iterative development approaches.",
      "Developed software planning documentation for authentication systems, payment integration, search functionality, ML-based counterfeit detection, and e-commerce workflows.",
      "Produced architectural spike and proof-of-concept analysis for evaluating technical feasibility and business requirements.",
      "Conducted project planning, retrospective analysis, and Agile methodology comparison between DSDM and Kanban approaches.",
    ],
    github: null,
    demo: null,
  },
  gotham: {
    title: "Gotham City College — Hybrid Teaching Network Design",
    subtitle: "Computer Networks · NCC L4",
    period: "NCC Education",
    role: "Network Designer",
    org: "NCC Education",
    tech: ["VLAN", "WiFi 6", "VPN", "Firewall", "Ubuntu Server", "Cisco IOS"],
    bullets: [
      "Designed a scalable hybrid teaching network infrastructure for an educational institution supporting classrooms, servers, wireless access points, printers, and BYOD connectivity.",
      "Planned network topology, VLAN segmentation, IP addressing, wireless mesh networking, and WiFi 6 deployment for secure and efficient classroom isolation.",
      "Evaluated infrastructure technologies including Ubuntu Server, Cisco IOS, VPNs, PoE-enabled access points, CAT6a cabling, file servers, and print servers.",
      "Conducted network security analysis involving firewalls, ransomware protection, phishing prevention, antivirus strategies, remote-access VPN implementation, and physical security controls.",
      "Designed scalable network architecture with backup servers, CCTV integration, wireless site surveys, and future-proofing recommendations for long-term infrastructure growth.",
      "Analyzed IoT integration risks, IPv6 considerations, network monitoring tools, and enterprise network management concepts.",
    ],
    github: null,
    demo: null,
  },
  walmart: {
    title: "Walmart Retail Sales Database System",
    subtitle: "Database Design & SQL · NCC L5",
    period: "NCC Education",
    role: "Database Designer · SQL Developer",
    org: "NCC Education",
    tech: ["SQL Server", "SQL", "ERD", "Normalization"],
    bullets: [
      "Designed and developed a relational retail sales database system using SQL Server and SQL.",
      "Created ER diagrams, data dictionaries, normalization processes (1NF–3NF), and relational database structures for retail management workflows.",
      "Implemented database tables, primary/foreign key constraints, joins, views, and advanced SQL queries for customer, product, supplier, order, and inventory management.",
      "Developed SQL scripts for database creation, data population, reporting queries, and transaction-related operations.",
      "Applied concepts including distributed databases, data warehousing, ETL, OLTP, OLAP, and database optimization techniques.",
      "Performed database assessment, denormalization analysis, derived data handling, and query performance considerations.",
    ],
    github: null,
    demo: null,
  },
  fitness: {
    title: "Fitness Tracker Desktop Application",
    subtitle: "Object-Oriented Programming · NCC L4",
    period: "NCC Education",
    role: "Desktop Application Developer",
    org: "NCC Education",
    tech: ["C#", "WinForms", "SQL Server", "OOP"],
    bullets: [
      "Developed a fitness-tracking desktop application using C#, Windows Forms, and SQL Server.",
      "Implemented user registration, login, activity tracking, MET-based calorie calculation, goal management, and daily activity search/reporting.",
      "Applied OOP principles including encapsulation (UserModel), modular form design, input validation, and reusable data handling.",
      "Built CRUD operations, automated ID generation, and dynamic data binding using DataTables, DataGridViews, and typed DataSets / TableAdapters.",
      "Designed clear desktop workflows with validation controls and data grids for managing user and activity records.",
      "Produced testing plans, algorithms, class diagrams, and technical documentation as part of the project lifecycle.",
    ],
    github: "fitness",
    demo: null,
  },
  mcdonalds: {
    title: "McDonald's Restaurant Database System",
    subtitle: "Database Design & SQL · NCC L4",
    period: "NCC Education",
    role: "Database Designer · SQL Developer",
    org: "NCC Education",
    tech: ["SQL", "ERD", "Normalization"],
    bullets: [
      "Designed and developed a relational restaurant management database system for customer, order, menu, and ingredient management.",
      "Created ER diagrams, data dictionaries, normalization processes (1NF–3NF), and relational database structures for restaurant operations.",
      "Implemented SQL tables, primary/foreign key relationships, CRUD operations, joins, filtering queries, and transaction-related data handling.",
      "Developed database queries for customer orders, menu management, ingredient tracking, order cancellation, and reporting functionalities.",
      "Applied database design principles including data integrity, entity relationships, normalization, and structured business process analysis.",
    ],
    github: null,
    demo: null,
  },
  fordley: {
    title: "Fordley Car Parking Office System",
    subtitle: "Office Solutions Development · NCC L4",
    period: "NCC Education",
    role: "System Analyst · Office Solutions Developer",
    org: "NCC Education",
    tech: ["Excel VBA", "Mail Merge", "ERD", "SQL Server Concepts"],
    bullets: [
      "Designed office solution workflows for a smart car parking management system including payment processing, membership handling, vehicle entry/exit processing, and security monitoring.",
      "Developed interactive Excel VBA forms with validation controls, automated workflows, and macro-based user interaction features.",
      "Applied Microsoft Word Mail Merge functionality for automated membership registration and document generation processes.",
      "Created ER diagrams, conceptual process diagrams, and database relationship structures for parking management operations.",
      "Conducted analysis of Microsoft Access and SQL Server advantages, scalability considerations, and database management approaches for enterprise systems.",
      "Evaluated end-user development strategies including UI/UX usability, user training, accessibility, and IT support considerations.",
    ],
    github: null,
    demo: null,
  },
  connect4: {
    title: "Connect 4 Desktop Game Application",
    subtitle: "Introduction to Programming · NCC L3",
    period: "NCC Education",
    role: "Desktop Application Developer",
    org: "NCC Education",
    tech: ["Visual Basic .NET", "WinForms", "File Handling"],
    bullets: [
      "Developed a Connect 4 desktop game application using Visual Basic .NET and Windows Forms.",
      "Implemented turn-based game logic, win-condition algorithms, dynamic grid updates, and multi-form navigation systems.",
      "Built save/load game functionality using file handling and persistent game-state management.",
      "Applied arrays, conditional logic, event-driven programming, validation techniques, and reusable programming structures.",
      "Designed user interfaces, object definition sheets, pseudocode, testing documentation, and installation procedures for the application lifecycle.",
    ],
    github: null,
    demo: null,
  },
  computersystems: {
    title: "Computer Systems Practical Portfolio",
    subtitle: "System Support & Maintenance · NCC L4",
    period: "NCC Education",
    role: "System Support Technician",
    org: "NCC Education",
    tech: ["Windows 10", "Hardware Troubleshooting", "Drivers", "Antivirus"],
    bullets: [
      "Performed Windows 10 installation, driver configuration, antivirus setup, office software installation, and utility software deployment.",
      "Diagnosed and resolved hardware and software issues including RAM faults, CPU fan problems, graphics driver issues, and device configuration errors.",
      "Conducted PC maintenance tasks such as OS updates, driver updates, malware scanning, disk maintenance, and system performance optimization.",
      "Documented troubleshooting procedures, maintenance processes, and IT infrastructure recommendations for a retail business environment.",
      "Applied system analysis, hardware diagnostics, preventive maintenance, and technical support practices in practical lab scenarios.",
    ],
    github: null,
    demo: null,
  },
};

const PROJECT_CATEGORIES = [
  { id: "web", label: "Web", ids: ["portal", "elitearticles", "libraria", "smcworld", "camping"] },
  { id: "mobile", label: "Mobile", ids: ["mhike-android", "mhike-rn", "android"] },
  { id: "ux", label: "UI/UX", ids: ["nature"] },
  { id: "analysis", label: "Analysis", ids: ["brightcare", "infinity", "wellcome", "geekup", "gotham"] },
  { id: "other", label: "Database & Desktop", ids: ["walmart", "fitness", "mcdonalds", "fordley", "connect4", "computersystems"] },
];
